Task/keyword classes pre ts
elixir-europe/json-schema-validator pull request #1
Opened 2019-11-26 14:14 UTC by rolando-ebi

2019-11-26 16:14 UTC, haseeb-gh commented on isChildTermOf
> +  console.warn node_modules/ajv/lib/ajv.js:385
i think this file got created by a test or something. it should be ok to delete it.

2019-11-26 16:20 UTC, haseeb-gh requested changes
there is an extra file in the root 'isChildTermOf' that should be ok to remove.

2019-11-26 17:19 UTC, haseeb-gh approved these changes

2019-11-28 13:22 UTC, javfg approved these changes

2019-12-02 13:48 UTC, merged